"""Structured error codes for the Godot AI protocol."""

from enum import StrEnum


class ErrorCode(StrEnum):
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    COMMAND_TIMEOUT = "COMMAND_TIMEOUT"
    EDITED_SCENE_MISMATCH = "EDITED_SCENE_MISMATCH"
    EDITOR_NOT_READY = "EDITOR_NOT_READY"
    INVALID_PARAMS = "INVALID_PARAMS"
    PLUGIN_DISCONNECTED = "PLUGIN_DISCONNECTED"
    UNKNOWN_COMMAND = "UNKNOWN_COMMAND"
    INTERNAL_ERROR = "INTERNAL_ERROR"
