"""Tests for the local interactive self-update smoke harness."""

from __future__ import annotations

import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "script" / "local-self-update-smoke"


def test_self_update_smoke_harness_prepares_fixture(tmp_path: Path) -> None:
    project = tmp_path / "self-update-smoke"

    result = subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--no-launch",
            "--project-dir",
            str(project),
            "--base-version",
            "2.2.0",
            "--next-version",
            "2.2.1-self-update-smoke",
        ],
        cwd=ROOT,
        check=True,
        text=True,
        capture_output=True,
    )

    assert "Self-update smoke fixture ready" in result.stdout
    assert "click Update" in result.stdout
    assert "a new Godot*.ips" in result.stdout

    base_cfg = (project / "addons" / "godot_ai" / "plugin.cfg").read_text()
    assert 'version="2.2.0"' in base_cfg

    base_dock = (project / "addons" / "godot_ai" / "mcp_dock.gd").read_text()
    assert 'const SELF_UPDATE_SMOKE_DOWNLOAD_URL := "smoke://local-prestaged"' in base_dock
    assert (
        'const SELF_UPDATE_SMOKE_ZIP := "res://self_update_smoke/godot-ai-plugin-vnext.zip"'
        in base_dock
    )
    assert "FileAccess.get_file_as_bytes(src)" in base_dock
    assert "user-update-path.txt" in base_dock

    base_configurator = (project / "addons" / "godot_ai" / "client_configurator.gd").read_text()
    assert "const DEFAULT_HTTP_PORT := 18000" in base_configurator
    assert "const DEFAULT_WS_PORT := 19500" in base_configurator
    assert 'const SELF_UPDATE_SMOKE_SERVER_VERSION := "2.2.0"' in base_configurator
    assert "var version := SELF_UPDATE_SMOKE_SERVER_VERSION" in base_configurator
    assert "godot_ai_self_update_smoke/excluded_domains" in base_configurator
    assert "return default_port" in base_configurator
    assert "static func ensure_settings_registered() -> void:" in base_configurator
    assert "static func _register_port_setting(" in base_configurator

    base_plugin = (project / "addons" / "godot_ai" / "plugin.gd").read_text()
    assert "godot_ai_self_update_smoke/managed_server_pid" in base_plugin

    zip_path = project / "self_update_smoke" / "godot-ai-plugin-vnext.zip"
    assert zip_path.exists()
    with zipfile.ZipFile(zip_path) as zf:
        names = set(zf.namelist())
        assert "addons/godot_ai/plugin.cfg" in names
        assert "addons/godot_ai/mcp_dock.gd" in names
        vnext_cfg = zf.read("addons/godot_ai/plugin.cfg").decode()
        vnext_dock = zf.read("addons/godot_ai/mcp_dock.gd").decode()
        vnext_configurator = zf.read("addons/godot_ai/client_configurator.gd").decode()
        vnext_plugin = zf.read("addons/godot_ai/plugin.gd").decode()

    assert 'version="2.2.1-self-update-smoke"' in vnext_cfg
    assert "smoke://local-prestaged" not in vnext_dock
    assert 'var _self_update_smoke_trigger: Dictionary = {"armed": true}' in vnext_dock
    assert 'var _self_update_smoke_array_trigger: Array[String] = ["armed"]' in vnext_dock
    assert "MCP | [self-update-smoke vnext _exit_tree]" in vnext_dock
    assert "const DEFAULT_HTTP_PORT := 18000" in vnext_configurator
    assert 'const SELF_UPDATE_SMOKE_SERVER_VERSION := "2.2.0"' in vnext_configurator
    assert 'godot-ai==%s" % version' in vnext_configurator
    assert "var version := SELF_UPDATE_SMOKE_SERVER_VERSION" in vnext_configurator
    assert "godot_ai_self_update_smoke/excluded_domains" in vnext_configurator
    assert "return default_port" in vnext_configurator
    assert "static func ensure_settings_registered() -> void:" in vnext_configurator
    assert "static func _register_port_setting(" in vnext_configurator
    assert "godot_ai_self_update_smoke/managed_server_pid" in vnext_plugin


def test_self_update_smoke_harness_refuses_unmarked_existing_dir(tmp_path: Path) -> None:
    project = tmp_path / "existing-project"
    project.mkdir()
    (project / "project.godot").write_text("not generated by the harness\n")

    result = subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--no-launch",
            "--project-dir",
            str(project),
        ],
        cwd=ROOT,
        text=True,
        capture_output=True,
    )

    assert result.returncode != 0
    assert "not marked as a smoke fixture" in result.stderr


def test_self_update_smoke_harness_refuses_suspicious_marker(tmp_path: Path) -> None:
    project = tmp_path / "existing-project"
    (project / ".godot-ai-self-update-smoke").mkdir(parents=True)
    (project / ".godot-ai-self-update-smoke" / "marker.txt").write_text("marker\n")
    (project / "project.godot").write_text("not generated by the harness\n")

    result = subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--no-launch",
            "--project-dir",
            str(project),
        ],
        cwd=ROOT,
        text=True,
        capture_output=True,
    )

    assert result.returncode != 0
    assert "has a smoke marker but does not look generated" in result.stderr
